### PR TITLE
Client server is setup

### PR DESCRIPTION
**Pull request by HenokSamuel**
- Set up the client folder that contains two folders src and dist
- The src folder contains a components folder with all the react components and an index.js file that renders the main component to our html file which is in the dist folder
- Used webpack and babel to serve and transpile the code for our browser

### CODE REVIEW

**Review by Evtaft22 — DISMISSED** [review]
webpack, babel, and client side has been setup with react component files and index.html

**Review by DennisPintilie — DISMISSED** [review]
Looks good

**Review by bsbrionesOS — APPROVED** [review]
Resolved  merged conflicts,

**Review by Evtaft22 — APPROVED** [review]
merge conflicts handled

**Pull request merged**
